server:
    port: 8080
spring:
    application:
        name: ManageCustomer
    datasource:
        driver-class-name: org.postgresql.Driver
        password: root
        url: jdbc:postgresql://172.22.0.2:5432/Customer
        username: postgres
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                format_sql: true
        show-sql: true

