server:
  port: 8083
spring:
  application:
    name: notification
  datasource:
    driver-class-name: org.postgresql.Driver
    password: root
    url: jdbc:postgresql://172.18.0.2:5432/notification
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
